### ISSUE TITLE
Employees administration panel pages

### ISSUE THREAD

**Issue by joeseggie** [resourceidea/resourceideaui#8]
Pages in the administration panel that will be used to manage the employees information.

**Scenario 1:**
GIVEN a user
WHEN viewing employees in an organization
THEN a page listing employees in the organization is displayed.

**Scenario 2:**
GIVEN a user
WHEN viewing employee information in an organization
THEN a page showing employee information is displayed.

**Scenario 3:**
GIVEN a user
WHEN editing employee information
THEN the page showing employee information is displayed and changes made to the information are saved and persisted in the database.

**Scenario 3:**
GIVEN a user
WHEN adding an employee
THEN a page displayed that captures new employee information is displayed.

**Task list**
==========

- [x]  Page to list employees.
- [x]  Page to view and edit employee details.
- [x]  Page to add new employee.
